apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: tp-inv-eureka
spec:
  selector:
    app: tp-inv-eureka
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30036
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-inv-eureka
  labels:
    app: tp-inv-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-inv-eureka
  template:
    metadata:
      labels:
        app: tp-inv-eureka
    spec:
      containers:
        - name: tp-inv-eureka
          image: mosofty/tp-inv-eureka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "stg"